package com.baiyang.oms.rest.wsdl.xml.client;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2017-11-13T16:32:21.730+08:00
 * Generated source version: 2.7.14
 * 
 */
@WebServiceClient(name = "enteTransportFilesService", 
                  wsdlLocation = "file:/E:/huangdao/enteTransportFiles.wsdl",
                  targetNamespace = "http://entetransportfiles.ws.service.transmit.sdeport.com") 
public class EnteTransportFilesService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://entetransportfiles.ws.service.transmit.sdeport.com", "enteTransportFilesService");
    public final static QName EnteTransportRecvFilesServiceImplPort = new QName("http://entetransportfiles.ws.service.transmit.sdeport.com", "EnteTransportRecvFilesServiceImplPort");
    public final static QName EnteTransportSendFilesServiceImplPort = new QName("http://entetransportfiles.ws.service.transmit.sdeport.com", "EnteTransportSendFilesServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/E:/huangdao/enteTransportFiles.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(EnteTransportFilesService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/E:/huangdao/enteTransportFiles.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public EnteTransportFilesService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public EnteTransportFilesService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EnteTransportFilesService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EnteTransportFilesService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EnteTransportFilesService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public EnteTransportFilesService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IEnteTransportRecvFilesService
     */
    @WebEndpoint(name = "EnteTransportRecvFilesServiceImplPort")
    public IEnteTransportRecvFilesService getEnteTransportRecvFilesServiceImplPort() {
        return super.getPort(EnteTransportRecvFilesServiceImplPort, IEnteTransportRecvFilesService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEnteTransportRecvFilesService
     */
    @WebEndpoint(name = "EnteTransportRecvFilesServiceImplPort")
    public IEnteTransportRecvFilesService getEnteTransportRecvFilesServiceImplPort(WebServiceFeature... features) {
        return super.getPort(EnteTransportRecvFilesServiceImplPort, IEnteTransportRecvFilesService.class, features);
    }
    /**
     *
     * @return
     *     returns IEnteTransportSendFilesService
     */
    @WebEndpoint(name = "EnteTransportSendFilesServiceImplPort")
    public IEnteTransportSendFilesService getEnteTransportSendFilesServiceImplPort() {
        return super.getPort(EnteTransportSendFilesServiceImplPort, IEnteTransportSendFilesService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IEnteTransportSendFilesService
     */
    @WebEndpoint(name = "EnteTransportSendFilesServiceImplPort")
    public IEnteTransportSendFilesService getEnteTransportSendFilesServiceImplPort(WebServiceFeature... features) {
        return super.getPort(EnteTransportSendFilesServiceImplPort, IEnteTransportSendFilesService.class, features);
    }

}
