
package com.baiyang.oms.rest.wsdl.xml.client;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2017-11-13T16:32:21.725+08:00
 * Generated source version: 2.7.14
 * 
 */
 
public class IEnteTransportRecvFilesService_EnteTransportRecvFilesServiceImplPort_Server{

    protected IEnteTransportRecvFilesService_EnteTransportRecvFilesServiceImplPort_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new IEnteTransportRecvFilesServiceImpl();
        String address = "https://testedi1200.sditds.com:6700/service_1501_webservice/ws/edi/EnteTransportRecvFiles";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws Exception {
        new IEnteTransportRecvFilesService_EnteTransportRecvFilesServiceImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
