
package com.baiyang.oms.rest.wsdl.xml.client;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2017-11-13T16:32:21.728+08:00
 * Generated source version: 2.7.14
 * 
 */
 
public class IEnteTransportSendFilesService_EnteTransportSendFilesServiceImplPort_Server{

    protected IEnteTransportSendFilesService_EnteTransportSendFilesServiceImplPort_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new IEnteTransportSendFilesServiceImpl();
        String address = "https://testedi1200.sditds.com:6700/service_1501_webservice/ws/edi/EnteTransportSendFiles";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws Exception {
        new IEnteTransportSendFilesService_EnteTransportSendFilesServiceImplPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
