package com.baiyang.oms.rest.wsdl.xml.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2017-11-13T16:32:21.720+08:00
 * Generated source version: 2.7.14
 * 
 */
@WebService(targetNamespace = "http://entetransportfiles.ws.service.transmit.sdeport.com", name = "IEnteTransportSendFilesService")
@XmlSeeAlso({ObjectFactory.class})
public interface IEnteTransportSendFilesService {

    @WebResult(name = "uploadFiles", targetNamespace = "")
    @RequestWrapper(localName = "uploadFiles", targetNamespace = "http://entetransportfiles.ws.service.transmit.sdeport.com", className = "com.baiyang.oms.rest.wsdl.xml.client.UploadFiles")
    @WebMethod
    @ResponseWrapper(localName = "uploadFilesResponse", targetNamespace = "http://entetransportfiles.ws.service.transmit.sdeport.com", className = "com.baiyang.oms.rest.wsdl.xml.client.UploadFilesResponse")
    public EnteUploadFilesResponse uploadFiles(
            @WebParam(name = "enteUploadFilesRequest", targetNamespace = "")
                    EnteUploadFilesRequest enteUploadFilesRequest,
            @WebParam(name = "expandAttribute", targetNamespace = "")
                    ExpandAttribute expandAttribute
    );
}
