
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.baiyang.oms.rest.wsdl.xml.client;

import javax.jws.WebService;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2017-11-13T16:32:21.690+08:00
 * Generated source version: 2.7.14
 * 
 */

@WebService(
                      serviceName = "enteTransportFilesService",
                      portName = "EnteTransportRecvFilesServiceImplPort",
                      targetNamespace = "http://entetransportfiles.ws.service.transmit.sdeport.com",
                      wsdlLocation = "file:/E:/huangdao/enteTransportFiles.wsdl",
                      endpointInterface = "com.baiyang.oms.rest.wsdl.xml.client.IEnteTransportRecvFilesService")

public class IEnteTransportRecvFilesServiceImpl implements IEnteTransportRecvFilesService {

    private static final Logger LOG = Logger.getLogger(IEnteTransportRecvFilesServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.sdeport.transmit.ws.client.IEnteTransportRecvFilesService#notifySdeportDownloadSuccess(com.sdeport.transmit.ws.client.EnteLoginInfo  enteLoginInfo ,)java.lang.String  fileTempID ,)com.sdeport.transmit.ws.client.ExpandAttribute  expandAttribute )*
     */
    public EnteDownloadSuccessResponse notifySdeportDownloadSuccess(EnteLoginInfo enteLoginInfo,String fileTempID,ExpandAttribute expandAttribute) {
        LOG.info("Executing operation notifySdeportDownloadSuccess");
        System.out.println(enteLoginInfo);
        System.out.println(fileTempID);
        System.out.println(expandAttribute);
        try {
            EnteDownloadSuccessResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.sdeport.transmit.ws.client.IEnteTransportRecvFilesService#waitDownloadList(com.sdeport.transmit.ws.client.EnteLoginInfo  enteLoginInfo ,)com.sdeport.transmit.ws.client.ExpandAttribute  expandAttribute )*
     */
    public EnteWaitDownloadFileListResponse waitDownloadList(EnteLoginInfo enteLoginInfo,ExpandAttribute expandAttribute) {
        LOG.info("Executing operation waitDownloadList");
        System.out.println(enteLoginInfo);
        System.out.println(expandAttribute);
        try {
            EnteWaitDownloadFileListResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.sdeport.transmit.ws.client.IEnteTransportRecvFilesService#downloadOneFile(com.sdeport.transmit.ws.client.EnteLoginInfo  enteLoginInfo ,)java.lang.String  fileTempID ,)com.sdeport.transmit.ws.client.ExpandAttribute  expandAttribute )*
     */
    public EnteDownloadOneFileResponse downloadOneFile(EnteLoginInfo enteLoginInfo,String fileTempID,ExpandAttribute expandAttribute) {
        LOG.info("Executing operation downloadOneFile");
        System.out.println(enteLoginInfo);
        System.out.println(fileTempID);
        System.out.println(expandAttribute);
        try {
            EnteDownloadOneFileResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
