
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.baiyang.oms.rest.wsdl.xml.client;

import javax.jws.WebService;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 2.7.14
 * 2017-11-13T16:32:21.704+08:00
 * Generated source version: 2.7.14
 * 
 */

@WebService(
        serviceName = "enteTransportFilesService",
        portName = "EnteTransportSendFilesServiceImplPort",
        targetNamespace = "http://entetransportfiles.ws.service.transmit.sdeport.com",
        wsdlLocation = "file:/E:/huangdao/enteTransportFiles.wsdl",
        endpointInterface = "com.baiyang.oms.rest.wsdl.xml.client.IEnteTransportSendFilesService")

public class IEnteTransportSendFilesServiceImpl implements IEnteTransportSendFilesService {

    private static final Logger LOG = Logger.getLogger(IEnteTransportSendFilesServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.sdeport.transmit.ws.client.IEnteTransportSendFilesService#uploadFiles(com.sdeport.transmit.ws.client.EnteUploadFilesRequest  enteUploadFilesRequest ,)com.sdeport.transmit.ws.client.ExpandAttribute  expandAttribute )*
     */
    public EnteUploadFilesResponse uploadFiles(EnteUploadFilesRequest enteUploadFilesRequest,ExpandAttribute expandAttribute) {
        LOG.info("Executing operation uploadFiles");
        System.out.println(enteUploadFilesRequest);
        System.out.println(expandAttribute);
        try {
            EnteUploadFilesResponse _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
